authbucketoauth2bundle:
    prefix:     /api/oauth2
    resource:   "@AuthBucketOAuth2Bundle/Resources/config/routing.yml"

app:
    prefix: /
    resource:   "@AppBundle/Resources/config/routing.yml"
