# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    user_manager:
        class: Doctrine\ORM\EntityManager
        factory: ["@doctrine", getManagerForClass]
        arguments: ["AppBundle:User"]

    user_repository:
        class: AppBundle\Repository\UserRepository
        factory: ["@user_manager", getRepository]
        arguments: ["AppBundle:User"]

    user_provider:
        class: AppBundle\User\UserProvider
        arguments: ["@user_repository"]
